### ISSUE TITLE
Step 1: extract code for triggering a download

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/occ-processing-lifewatch#4]
Take code in [`1_download.Rmd`](https://github.com/trias-project/occ-processing/blob/master/src/belgium/1_download.Rmd) and put it in a .R file.

**Comment by skoulouzis** [comment]
provide inputarguments to R scripts use: 'args = commandArgs(trailingOnly=TRUE)'
Example: 

args = commandArgs(trailingOnly=TRUE)
orkingdirectory=args[1]
num = as.numeric(args[2])
